

services:
  app:
    build: .
    container_name: devops-platform-app
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./app:/app                    # для hot-reload кода Python
      - ./frontend:/app/frontend      # для hot-reload фронтенда
      - /var/run/docker.sock:/var/run/docker.sock  # для доступа к другим контейнерам
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload   # ← hot-reload
    restart: unless-stopped
    networks:
      - monitoring
    privileged: true          # доступ к docker.sock
      
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    restart: unless-stopped
  
networks:
  monitoring:
    driver: bridge
volumes:
  grafana_data: